version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: rust-toolchain
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  groups:
    wasm-tools:
      patterns:
      - wasm-compose
      - wasm-metadata
      - wit-component
- package-ecosystem: devcontainers
  directory: "/"
  schedule:
    interval: weekly
