[package]
name = "factory"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[features]
debug = []

[dependencies]
anyhow = { workspace = true }
static-config = { workspace = true }
wit-bindgen = { workspace = true }
