@since(version = 0.3.0-dev)
interface factory {
    use componentized:component/types@0.1.0.{wasm, error-code};

    /// Create a component implementing `wasi:config/store` with the provided values.
    @since(version = 0.3.0-dev)
    create: func(values: list<tuple<string, string>>) -> result<wasm, error-code>;
}