[package]
name = "adapter"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[features]
debug = []

[dependencies]
anyhow = { workspace = true }
bytes = "1.10.0"
wit-bindgen = { workspace = true }
